### ISSUE TITLE
Main EasyTrain

### ISSUE THREAD

**Issue by fallmpro** [fallmpro/JAVA_FALL#1]
Bonjour Madame, pouvez-vous me donner un retour sur le fichier main.java d'EasyTrain svp ?

Merci d'avance.

**Comment by zoubeidada** [comment]
@fallmpro la prochaine fois, il serait bien d'avoir un lien vers le document à vérifier pour faciliter mon boulot :-)

Le main ne teste pas toutes les fonctions de toutes les classes !!
Il faut tester les constructeurs et les setters et les getters pour voir s'ils font le travail ;-) 

Bon Dimanche
